#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
types:
  
    email:
      type: string
      minLength: 1
      pattern: ^/.*$
      
    baa:
      type: object
      properties:
        first: integer
        second: string
  
    foo:
      type: object
      properties:
        prop: baa | email | boolean | integer | nil

# annotation iterable with items [(annotation type <com.fasterxml.jackson.databind.annotation.JsonSerialize> and member iterable containing [contents "BaaEmailBooleanIntegerNilUnion.Serializer.class"]), (annotation type <com.fasterxml.jackson.databind.annotation.JsonDeserialize> and member iterable containing [contents "BaaEmailBooleanIntegerNilUnion.Deserializer.class"])] in any order and inner type iterable containing [(type name is "Serializer" and method iterable containing [(method name "<init>"), (method name "serialize")]), (type name is "Deserializer" and method iterable with items [(method name "<init>"), (method name "isValidObject"), (method name "getNullValue"), (method name "deserialize")] in any order), (type name is "UnionType")])
# annotation iterable with items [(annotation type <com.fasterxml.jackson.databind.annotation.JsonSerialize> and member iterable containing [contents "BaaEmailBooleanIntegerNilUnion.Serializer.class"]), (annotation type <com.fasterxml.jackson.databind.annotation.JsonDeserialize> and member iterable containing [contents "BaaEmailBooleanIntegerNilUnion.Deserializer.class"])] in any order annotation not matched: <@com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = PropUnion.Deserializer.class)>