#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
types:
    inherited:
      properties:
        age: integer
    foo:
        type: inherited
        properties:
          name: string

