#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
types:
    once:
      additionalProperties: false
      discriminator: kind
      properties:
        kind: string
        right: string
    foo:
        type: once
        additionalProperties: false
        discriminatorValue: myOwnValue
        properties:
          name: string

