#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
types:
    foo:
        type: object
        properties:
          unionOfPrimitives:
            type: string | integer
          unionOfOthers:
            type: One | Two
    One:
      properties:
        oneProp: string
    Two:
      properties:
        twoProp: string
