#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
types:
    foo:
        type: object
        properties:
          name:
            type: string
            enum: [One, Two]
          int:
            type: integer
            enum: [1, 2]
          num:
            type: number
            enum: [1, 2]
