#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
types:
    once:
      additionalProperties: false
      properties:
        right: string
    twice:
      additionalProperties: false
      properties:
        left: string
    foo:
      additionalProperties: false
      type: [once, twice]
      properties:
        name: string

