#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
uses:
  ramltopojo: ramltopojo.raml
(ramltopojo.types):
  - name: core.one
    arguments: [ foo, bar ]

types:
    foo:
        type: object
        properties:
          name: string
          lastName: string
