#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
uses:
  ramltopojo: ramltopojo.raml
(ramltopojo.types):
  plugins: [core.one]

types:
    foo:
        type: object
        properties:
          name: string
          lastName: string
