#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
types:
    foo:
        type: object
        properties:
          name:
            type: string
            required: false
          age:
            type: integer
            required: true
