#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
types:
    composed:
      properties:
        size: integer
    foo:
        type: object
        properties:
          name: composed

