#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
types:
    once:
      properties:
        right: string
    twice:
      properties:
        left: string
    union:
      type: once|twice
    foo:
        type: [once, twice]
        properties:
          name: string

