#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
uses:
  ramltopojo: ramltopojo.raml
  arrays: arrays.raml
  unions: unions.raml
  j1unions: unions-jackson1.raml
  enumerations: enumerations.raml
  discriminatorjackson: discriminator-jackson.raml
  biomes: biomes.raml
  conflict1: conflict1.raml
  conflict2: conflict2.raml
  conflict3: conflict3.raml
  xml: xml.raml
types:
  withAnArray:
    properties:
      someArray:
        type: integer[]
        (ramltopojo.plugins):
          - name: core.asArray
      anotherArray:
        type: dates[]
        (ramltopojo.plugins):
          - name: core.asArray
  dates:
    (ramltopojo.plugins):
      - name: core.jackson2
    properties:
      someDate: datetime
  foo:
    (ramltopojo.plugins):
      - name: core.equalsAndHashCode
      - name: core.jsr303
      - name: core.jackson2
    type: object
    discriminatorValue: myOwnValue
    properties:
      name:
        type: string
        pattern: a\[a-z\]b
      goo:
        type: object
        properties:
          glue: boolean
          flue:
            type: object
            properties:
              another: string
  eater:
    (ramltopojo.plugins):
      - name: core.equalsAndHashCode
        arguments: [name]
      - name: core.toString
    #          - name: core.jackson2
    additionalProperties: false
    type: object
    discriminatorValue: myOwnValue
    properties:
      name: string
      count: integer
      other: foo
  addPropsVerification:
    (ramltopojo.plugins):
      - name: core.jackson2
    type: object
    discriminatorValue: myOwnValue
    properties:
      name: string
      /note\d+/: string

  listElementParent:
    type: object
    properties:
      name: string

  listElementChild:
    type: listElementParent
    properties:
      name: string

  listHolderParent:
    type: object
    (ramltopojo.plugins):
      - name: core.wildcardcollection
        arguments: [java.lang.Object]
    properties:
      elements: listElementParent[]
      names: string[]
      id: integer

  listHolderChild:
    type: listHolderParent
    properties:
      elements: listElementChild[]


