#%RAML 1.0 Library
uses:
  ramltopojo: ramltopojo.raml
types:
  PetResponse:
    (ramltopojo.types):
        - name: core.jackson2
    type: object
    properties:
      myPet:
        type: Animal

  Animal:
    (ramltopojo.types):
        - name: core.jackson2
    type: object
    discriminator: animalType
    properties:
      animalType: string

  Cat:
    (ramltopojo.types):
        - name: core.jackson2
    type: Animal
    discriminatorValue: CAT
    properties:
      legs: integer

  Fish:
    (ramltopojo.types):
        - name: core.jackson2
    type: Animal
    discriminatorValue: FISH
    properties:
      fins: integer
