#%RAML 1.0 Library
uses:
  ramltopojo: ramltopojo.raml
types:
  Dog:
    (ramltopojo.plugins):
      - name: core.jackson2
    type: object
    properties:
      bark: nil | boolean
      color: string
  Television:
    (ramltopojo.plugins):
      - name: core.jackson2
    type: object
    properties:
      color: boolean
  Projector:
    (ramltopojo.plugins):
      - name: core.jackson2
    type: object
    properties:
      hanging: boolean
  Entertainement:
    (ramltopojo.plugins):
      - name: core.jackson2
    type: Television | Projector
  SomeScalar:
    (ramltopojo.plugins):
      - name: core.jackson2
    type: string|integer
  date1Union:
    (ramltopojo.plugins):
      - name: core.jackson2
    type: date-only | nil
  date2Union:
    (ramltopojo.plugins):
      - name: core.jackson2
    type: time-only | nil
  date3Union:
    (ramltopojo.plugins):
      - name: core.jackson2
    type: datetime-only | nil
  date4Union:
    (ramltopojo.plugins):
      - name: core.jackson2
    type: datetime | nil
  dateUnion:
    (ramltopojo.plugins):
      - name: core.jackson2
    type: object
    properties:
      date1: date1Union
      date2: date2Union
      date3: date3Union
      date4: date4Union
  nilString:
    (ramltopojo.plugins):
      - name: core.jackson2
    type: string | nil
  nilUnionType:
    (ramltopojo.plugins):
      - name: core.jackson2
    type: string|nil
  complexUnion:
    (ramltopojo.plugins):
      - name: core.jackson2
    type: boolean|integer|string|nil
  unionProperty:
    (ramltopojo.plugins):
      - name: core.jackson2
    properties:
      goo: nilString
      declared: nilUnionType

