#%RAML 1.0
#((ObjectNode)((NodeShape) others[0]).customDomainProperties().get(0).extension()).properties() == abstract / plugins
title: Hello World API
version: v1
baseUri: https://api.github.com
uses:
  ramltopojo: ramltopojo.raml
(ramltopojo.types):
    - name: core.one
      arguments: [ foo, bar ]
    - name: core.two
      arguments: [ alpha, gamma ]

types:
    foo:
        type: object
        (ramltopojo.types):
            - name: core.foo
              arguments: [ foo, bar ]
        properties:
          name: string
          lastName: string
#    too:
#        type: object
#        (ramltopojo.types):
#          plugins: [core.too, core.moo]