#%RAML 1.0
#((ObjectNode)((NodeShape) others[0]).customDomainProperties().get(0).extension()).properties() == abstract / plugins
title: Hello World API
version: v1
baseUri: https://api.github.com
uses:
  ramltopojo: ramltopojo.raml
(ramltopojo.plugins):
    - name: core.one
      arguments: [ foo, bar ]
    - name: core.two
      arguments: [ alpha, gamma ]

types:
    none:
      type: object
      properties:
        name: string
        lastName: string
    foo:
        type: object
        (ramltopojo.plugins):
            - name: core.foo
              arguments: [ foo, bar ]
        properties:
          name: string
          lastName: string
    too:
        type: object
        (ramltopojo.plugins):
          - name: core.too
          - name: core.moo
