#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
uses:
  libOne: lib1.raml
types:
  someint: integer
  foo:
    type: object
    properties:
      string: string
  somebool:
    type: object
    properties:
        gaa: string

/first:
  put:
    queryParameters:
      q1: integer
    headers:
      h1: integer
    body:
      application/json:
        type: libOne.haha
    responses:
      200:
        headers:
          h2: integer
        body:
          application/json:
            type: foo
  /deep:
    put:
      body:
        application/json:
          type: foo
