#%RAML 1.0 Library
annotationTypes:
    plugins:
        allowedTargets: [TypeDeclaration,API]
        type: array
        items:
          properties:
            name: string
            arguments?: string[] | any