#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
types:
  foo:
    type: object
    properties:
      string: string
      integer: integer
      number: number
      datetime-only: datetime-only
      boolean: boolean
      date-only: date-only
      datetime: datetime
      time-only: time-only
