#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com

# ------------------------------------------------------------------------------
# - TYPES
# ------------------------------------------------------------------------------     
     
types:
 
  DtoMediumString:
    type: string
    maxLength: 256
    
  DtoLongString:
    type: string
    maxLength: 4096
    
  DtoUuid:
    type: string
    pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
    
  DtoPath:
    type: DtoMediumString
    minLength: 1
    pattern: ^/.*$
    
  DtoId:
    type: DtoMediumString
    minLength: 1
    pattern: ^\S+$
    
  DtoHref:
    type: DtoMediumString
    minLength: 1
    pattern: ^https://.*$
    
  DtoTime:
    type: integer
    format: int64
    
  DtoSha1:
    type: string
    pattern: ^[a-f0-9]{40}$
    
  DtoSemVer:
    type: DtoMediumString
    pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$ 
    
  DtoTenantId:
    type: string
    pattern: ^[1-9]\d{2,}$
    example: '666'
    
  DtoQuery:
    type: string
    pattern: ;[^/]+
    #TODO

  # ------------------------------------------------------------------------------
  # Exceptions 
  # ------------------------------------------------------------------------------
  
  DtoException:
    type: object
    discriminator: _type
    properties:
      _type:
        type: string
    #TODO: Further properties
  DtoIllegalAuthenticationException:
    type: DtoException
    #TODO: Further properties
  DtoPermissionDeniedException:
    type: DtoException
    #TODO: Further properties
  DtoBodyParseException:
    type: DtoException
    #TODO: Further properties
  DtoValueInUseException:
    type: DtoException
    #TODO: Further properties
  DtoQuerySyntaxException:
    type: DtoException
    #TODO: Further properties
  DtoQueryResultException:
    type: DtoException
    #TODO: Further properties
        
  # ------------------------------------------------------------------------------
  # Database Entity 
  # ------------------------------------------------------------------------------ 
        
  DtoDatabaseEntity:
    type: object
    discriminator: _type
    properties:
      _type:
        type: string
      uuid?:
        type: DtoUuid
      path?:
        type: DtoPath
      id?:
        type: DtoId
      version?:
        type: integer
        format: int64
        minimum: 0
        default: 0
      label?:
        type: DtoMediumString
      description?:
        type: DtoLongString
      retentionPolicy?:
        type: DtoRetentionPolicy
      tags?:
        type: DtoTags
      createdBy?:
        type: DtoAuthor
      createdOn?:
        type: DtoTime
      updatedBy?:
        type: DtoAuthor
      updatedOn?:
        type: DtoTime
        
  DtoRetentionPolicy:
    type: object
    properties:
      deleteOn: 
        type: DtoTime | nil
        
  DtoTags:
    type: object
    properties:
      //:
        type: DtoMediumString
        minLength: 1
    
  DtoAuthor:
    type: object
    properties:
      id:
        type: DtoId
      label:
        type: DtoMediumString
      profileHref:
        type: DtoHref | nil


  # ------------------------------------------------------------------------------
  # App Info 
  # ------------------------------------------------------------------------------     
    
  DtoAppInfo:
    type: object
    properties:
      id:
        type: DtoId
      label:
        type: DtoMediumString
      description:
        type: DtoLongString
      project:
        type: DtoId
      vendor:
        type: DtoMediumString
      version:
        type: DtoSemVer
      build:
        type: DtoAppBuildInfo | nil
        
  DtoAppBuildInfo:
    type: object
    properties:
      id:
        type: DtoId
      time:
        type: DtoTime
      commit:
        type: DtoSha1

  DtoContact:
    type: DtoDatabaseEntity
    discriminatorValue: DtoContact
    properties:
      firstName:
        type: DtoMediumString
        minLength: 1
      surname:
        type: DtoMediumString
        minLength: 1
      email:
        type: DtoEmail | nil
      phone:
        type: DtoPhone | nil
        
  DtoEmail:
    type: DtoMediumString
    minLength: 1
    pattern: ^\S+@\S+$
    
  DtoPhone:
    type: DtoMediumString
    minLength: 1
    pattern: ^\+[1-9]\d \d+ \d+$    