#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
types:
    first:
      properties:
        age: integer
    second:
      properties:
        area: string
    foo:
        type: first|second